// Generated by scripts/gen-assistant-tabs.mjs. Do not edit by hand.
export const TABS = {
 "/sales": [
  {
   "label": "Enquiries",
   "href": "/sales/leads"
  },
  {
   "label": "Weekly Planner",
   "href": "/sales/planner"
  },
  {
   "label": "WhatsApp",
   "href": "/sales/whatsapp"
  },
  {
   "label": "Trade Requests",
   "href": "/sales/trade-requests"
  },
  {
   "label": "Customers",
   "href": "/sales/customers"
  },
  {
   "label": "Quotations",
   "href": "/sales/quotations"
  },
  {
   "label": "Sale Orders",
   "href": "/sales/sale-orders"
  },
  {
   "label": "AMC",
   "href": "/sales/amc"
  },
  {
   "label": "Order Tracker",
   "href": "/sales/payment-orders"
  },
  {
   "label": "Payment Log",
   "href": "/sales/payment-log"
  },
  {
   "label": "Invoices",
   "href": "/sales/invoices"
  },
  {
   "label": "Returns",
   "href": "/sales/returns"
  },
  {
   "label": "Library",
   "href": "/sales/library"
  },
  {
   "label": "Portal Access",
   "href": "/sales/portal-access"
  },
  {
   "label": "Products",
   "href": "/sales/products"
  },
  {
   "label": "Funnel Stages",
   "href": "/sales/funnel-stages"
  },
  {
   "label": "Targets",
   "href": "/sales/targets"
  },
  {
   "label": "Branches",
   "href": "/sales/branches"
  },
  {
   "label": "Email Templates",
   "href": "/sales/email-templates"
  },
  {
   "label": "My Email",
   "href": "/sales/email-setup"
  }
 ],
 "/procurement": [
  {
   "label": "Enquiry",
   "href": "/procurement/enquiry"
  },
  {
   "label": "Selection",
   "href": "/procurement/selection"
  },
  {
   "label": "Purchase Orders",
   "href": "/procurement/orders"
  },
  {
   "label": "Delivery Lots",
   "href": "/procurement/orders-lots"
  },
  {
   "label": "Overdues",
   "href": "/procurement/overdues"
  },
  {
   "label": "Status",
   "href": "/procurement/state"
  },
  {
   "label": "Returns",
   "href": "/procurement/returns"
  },
  {
   "label": "Vendor Bills",
   "href": "/procurement/vendor-bills"
  },
  {
   "label": "Roster",
   "href": "/procurement/suppliers-roster"
  },
  {
   "label": "Analysis",
   "href": "/procurement/suppliers-analysis"
  }
 ],
 "/stores": [
  {
   "label": "Inward",
   "href": "/stores/receive"
  },
  {
   "label": "Gate Entry",
   "href": "/stores/gir"
  },
  {
   "label": "Demand",
   "href": "/stores/requests"
  },
  {
   "label": "Trade Orders",
   "href": "/stores/trade"
  },
  {
   "label": "Indents",
   "href": "/stores/indents"
  },
  {
   "label": "Allocator",
   "href": "/stores/allocate"
  },
  {
   "label": "Macro Allocator",
   "href": "/stores/split-allocation"
  },
  {
   "label": "On Floor",
   "href": "/stores/issued"
  },
  {
   "label": "Stock Statement",
   "href": "/stores/statement"
  },
  {
   "label": "Inventory",
   "href": "/stores/inventory"
  }
 ],
 "/pr": [
  {
   "label": "Purchase Requests",
   "href": "/pr/raise"
  },
  {
   "label": "PR History",
   "href": "/pr/history"
  },
  {
   "label": "Release BOM",
   "href": "/pr/release"
  },
  {
   "label": "PR Templates",
   "href": "/pr/templates"
  },
  {
   "label": "Reorder Suggestions",
   "href": "/pr/reorder"
  }
 ],
 "/production/shop": [
  {
   "label": "Job Card",
   "href": "/production/shop/jobcards"
  },
  {
   "label": "Dispatch",
   "href": "/production/shop/dispatch"
  },
  {
   "label": "Material Indent",
   "href": "/production/shop/indent"
  },
  {
   "label": "Remnants",
   "href": "/production/shop/remnants"
  },
  {
   "label": "Workers",
   "href": "/production/shop/sheet"
  },
  {
   "label": "Approvals",
   "href": "/production/shop/approvals"
  }
 ],
 "/planning": [
  {
   "label": "Material Plan",
   "href": "/planning/plan"
  },
  {
   "label": "Schedule",
   "href": "/planning/schedule"
  },
  {
   "label": "Capacity",
   "href": "/planning/capacity"
  },
  {
   "label": "Cut",
   "href": "/planning/cut"
  },
  {
   "label": "Backlog",
   "href": "/planning/backlog"
  }
 ],
 "/qc": [
  {
   "label": "Certificates",
   "href": "/qc/tc-bank"
  },
  {
   "label": "Assign to Units",
   "href": "/qc/tc-assign"
  },
  {
   "label": "Test Records",
   "href": "/qc/test-records"
  },
  {
   "label": "Documents",
   "href": "/qc/docs"
  },
  {
   "label": "NCR",
   "href": "/qc/ncr"
  },
  {
   "label": "Job Cards",
   "href": "/qc/holds"
  },
  {
   "label": "Calibration",
   "href": "/qc/calibration"
  },
  {
   "label": "Inward",
   "href": "/qc/inward-approvals"
  },
  {
   "label": "Job Card Stages",
   "href": "/qc/jobsheet-approvals"
  },
  {
   "label": "Pre-Dispatch",
   "href": "/qc/predispatch-approvals"
  }
 ],
 "/dispatch": [
  {
   "label": "Packing Lists",
   "href": "/dispatch/board"
  },
  {
   "label": "Pending Items",
   "href": "/dispatch/pending"
  },
  {
   "label": "Shipments",
   "href": "/dispatch/shipments"
  },
  {
   "label": "Deliveries",
   "href": "/dispatch/deliveries"
  },
  {
   "label": "Documents",
   "href": "/dispatch/documents"
  },
  {
   "label": "Gate Passes",
   "href": "/dispatch/gatepasses"
  },
  {
   "label": "Approvals",
   "href": "/dispatch/approvals"
  }
 ],
 "/installation": [
  {
   "label": "Visits",
   "href": "/installation/visits"
  },
  {
   "label": "Documentation",
   "href": "/installation/docs"
  },
  {
   "label": "Progress Photos",
   "href": "/installation/photos"
  }
 ],
 "/service-expenses": [
  {
   "label": "Cash Requests",
   "href": "/service-expenses/cash"
  },
  {
   "label": "Travel Allowance",
   "href": "/service-expenses/travel"
  }
 ],
 "/hr": [
  {
   "label": "Employees",
   "href": "/hr/employees"
  },
  {
   "label": "Attendance",
   "href": "/hr/attendance"
  },
  {
   "label": "Leave",
   "href": "/hr/leave"
  },
  {
   "label": "Shifts",
   "href": "/hr/shifts"
  },
  {
   "label": "Holidays",
   "href": "/hr/holidays"
  },
  {
   "label": "Recruitment",
   "href": "/hr/recruitment"
  },
  {
   "label": "Payroll",
   "href": "/hr/payroll"
  },
  {
   "label": "Expenses",
   "href": "/hr/expenses"
  }
 ],
 "/accounts": [
  {
   "label": "Company Entities",
   "href": "/accounts/company-entities"
  },
  {
   "label": "Service Expenses",
   "href": "/accounts/service-expenses"
  },
  {
   "label": "GST & TDS Rates",
   "href": "/accounts/rates"
  },
  {
   "label": "General Ledger",
   "href": "/accounts/ledger"
  },
  {
   "label": "Fixed Assets",
   "href": "/accounts/fixed-assets"
  },
  {
   "label": "GST Returns",
   "href": "/accounts/gst-returns"
  },
  {
   "label": "Bank Reconciliation",
   "href": "/accounts/bank-reconciliation"
  },
  {
   "label": "Audit Log",
   "href": "/accounts/audit-log"
  }
 ],
 "/engineering": [
  {
   "label": "Item Master",
   "href": "/engineering/item-master"
  },
  {
   "label": "Design Sign-off",
   "href": "/engineering/design-signoff"
  },
  {
   "label": "BOMs",
   "href": "/engineering/structure"
  },
  {
   "label": "Structure Templates",
   "href": "/engineering/structure-templates"
  },
  {
   "label": "Subsystems",
   "href": "/engineering/subsystems"
  },
  {
   "label": "Where-Used",
   "href": "/engineering/where-used"
  },
  {
   "label": "Common / Uncommon",
   "href": "/engineering/common-uncommon"
  },
  {
   "label": "Change Notes",
   "href": "/engineering/ecn"
  },
  {
   "label": "Purchase Requests",
   "href": "/engineering/pr-raise"
  },
  {
   "label": "PR History",
   "href": "/engineering/pr-history"
  },
  {
   "label": "PR Templates",
   "href": "/engineering/pr-templates"
  },
  {
   "label": "Release BOM",
   "href": "/engineering/pr-release"
  }
 ],
 "/approvals": [
  {
   "label": "Devices",
   "href": "/approvals/devices"
  },
  {
   "label": "Browser",
   "href": "/approvals/browser"
  },
  {
   "label": "People",
   "href": "/approvals/people"
  },
  {
   "label": "Service Expenses",
   "href": "/approvals/service-expenses"
  },
  {
   "label": "Mail",
   "href": "/approvals/mail"
  }
 ]
};
