// lib/project-delete.js — "Delete Entire Project": PM + Design/Engineering Head only.
//
// Model: **review, then decide** — not a hard block. Almost everything real about a project
// (Purchase Orders, Vendor Bills, Sales Invoices, QC statutory documents, approved/customer-visible
// Drawings, Service Calls/Contracts, released Work Orders, logged Supplier Quotes, material actually
// received/issued) is surfaced with a document inventory (download links where a PDF exists) so the
// decider can look at everything real before choosing to proceed anyway. Nothing in that list is
// silently skipped or force-deleted without that explicit confirmation.
//
// The ONE genuine hard block, never overridable, is **live split-order children**
// (`projects.master_project_id`) — that's a structural fact about the multi-unit-split
// architecture, not a business judgment call, so there is nothing to "decide."
//
// How each reviewed category is actually handled once confirmed, chosen per-category so a real
// financial/compliance record is never silently corrupted:
//   - Purchase Orders  — only this project's own `po_items` rows are removed (a PO can legitimately
//     span several projects, §5c/§5bx); the PO header itself is removed too, but only once it has
//     zero items left. `purchase_orders` carries no stored total of its own (computed at read time),
//     so this never leaves a stale aggregate.
//   - Vendor Bills — `vendor_bill_items.bom_item_id` is nulled, never the row deleted: a bill DOES
//     carry stored totals (subtotal/tax/payable_amount) that a partial-item delete would corrupt.
//     Nulling severs the traceability link and leaves the bill, its totals, and any GL posting it
//     already made completely untouched.
//   - Sales Invoices — `project_id` (nullable) is nulled, the invoice itself (and its items/
//     payments/receipts/credit notes) is never deleted, for the identical reason: an issued/paid
//     invoice may have already posted a real journal entry with no reversal mechanism here.
//   - Supplier quotes — no explicit handling needed: `bom_item_id ON DELETE CASCADE` cleans them up
//     automatically the moment their bom_item is deleted below.
//   - Everything else in the review list (material received/issued, Packing Lists, QC statutory
//     documents + their parts, Drawings, Service Calls/Contracts, Work Orders) is genuinely
//     project-owned with no cross-project sharing and no external financial record — deleted outright.
//
// TIER 2 — everything never surfaced for review (BOM tree, milestones, job cards, calc sheets, scope
// of supply, etc.) is unconditionally project-owned and always deleted. Ordering was computed from
// the live schema (PRAGMA foreign_key_list, walked transitively from `projects`/`bom_items` — the
// same method lib/bom-item-guard.js's own list was generated by), leaves-first, so no NO-ACTION
// constraint is ever hit mid-way. Ownership tags on shared physical stock (stock_pieces/
// inventory_batches/inventory_serials) are nulled, never deleted — the material itself isn't project
// data. Active reservations are released the normal way (releaseReservationsForItem) first.

import { queryOne, queryAll, withTransaction } from './db';
import { releaseReservationsForItem } from './procurement';

const PO_PDF = id => `/api/purchase-orders/${id}/pdf`;
const VENDOR_BILL_PDF = id => `/api/vendor-bills/${id}/pdf`;
const INVOICE_PDF = id => `/api/sales-invoices/${id}/pdf`;
const PACKING_PDF = id => `/api/packing/${id}/pdf`;
const QC_DOC_PDF = id => `/api/qc-documents/${id}/pdf`;

async function bomItemIdsOf(projectId) {
  return (await queryAll('SELECT id FROM bom_items WHERE project_id = ?', [projectId])).map(r => r.id);
}

export async function getProjectDeletePreview(projectId) {
  const project = await queryOne('SELECT id, project_no FROM projects WHERE id = ?', [projectId]);
  if (!project) return null;

  const bomItemIds = await bomItemIdsOf(projectId);
  const inList = bomItemIds.length ? `(${bomItemIds.map(() => '?').join(',')})` : '(NULL)';

  const hardBlockers = [];
  const reviewItems = [];
  const add = (list, key, label, rows, hrefFn) => {
    if (!rows.length) return;
    list.push({
      key, label, count: rows.length,
      items: rows.map(r => ({ id: r.id, ref: r.ref, detail: r.detail || null, href: hrefFn ? hrefFn(r.id) : null })),
    });
  };
  const addCount = (key, label, n) => { if (n > 0) reviewItems.push({ key, label, count: n, items: [] }); };

  const children = await queryAll('SELECT id, project_no AS ref FROM projects WHERE master_project_id = ?', [projectId]);
  add(hardBlockers, 'split_children', 'Split units under this order — resolve these first, this can’t be reviewed away', children);

  const pos = bomItemIds.length ? await queryAll(
    `SELECT DISTINCT po.id, po.po_no AS ref, po.status AS detail
     FROM po_items pi JOIN purchase_orders po ON po.id = pi.po_id WHERE pi.bom_item_id IN ${inList}`, bomItemIds) : [];
  add(reviewItems, 'purchase_orders', 'Purchase Orders', pos, PO_PDF);

  const bills = bomItemIds.length ? await queryAll(
    `SELECT DISTINCT vb.id, vb.bill_no AS ref, vb.status AS detail
     FROM vendor_bill_items vbi JOIN vendor_bills vb ON vb.id = vbi.vendor_bill_id WHERE vbi.bom_item_id IN ${inList}`, bomItemIds) : [];
  add(reviewItems, 'vendor_bills', 'Vendor Bills', bills, VENDOR_BILL_PDF);

  const quoteCount = bomItemIds.length
    ? (await queryOne(`SELECT COUNT(*) AS n FROM supplier_quotes WHERE bom_item_id IN ${inList}`, bomItemIds))?.n || 0 : 0;
  addCount('supplier_quotes', 'Supplier quotes logged', quoteCount);

  const receivedCount = bomItemIds.length
    ? (await queryOne(
        `SELECT (SELECT COUNT(*) FROM bom_item_receipts WHERE bom_item_id IN ${inList}) +
                (SELECT COUNT(*) FROM material_issues WHERE bom_item_id IN ${inList}) AS n`,
        [...bomItemIds, ...bomItemIds]))?.n || 0 : 0;
  addCount('material_activity', 'Material received or issued to WIP', receivedCount);

  const invoices = await queryAll(
    `SELECT id, invoice_no AS ref, status AS detail FROM sales_invoices WHERE project_id = ?`, [projectId]);
  add(reviewItems, 'sales_invoices', 'Sales Invoices', invoices, INVOICE_PDF);

  const packing = await queryAll(
    `SELECT id, packing_no AS ref, status AS detail FROM packing_lists WHERE project_id = ?`, [projectId]);
  add(reviewItems, 'packing_lists', 'Packing Lists', packing, PACKING_PDF);

  const qcDocs = await queryAll(
    `SELECT id, doc_id AS ref, series AS detail FROM qc_documents WHERE project_id = ? AND customer_visible = 1`, [projectId]);
  add(reviewItems, 'qc_documents', 'QC statutory documents shared with the customer', qcDocs, QC_DOC_PDF);

  const drawings = await queryAll(
    `SELECT id, name AS ref, status AS detail FROM calc_drawings
     WHERE project_id = ? AND (customer_visible = 1 OR status IN ('approved', 'as_built'))`, [projectId]);
  add(reviewItems, 'calc_drawings', 'Approved / customer-visible drawings', drawings);

  const serviceCalls = await queryAll(`SELECT id, call_no AS ref, subject AS detail FROM service_calls WHERE project_id = ?`, [projectId]);
  add(reviewItems, 'service_calls', 'Service calls', serviceCalls);

  const serviceContracts = await queryAll(`SELECT id, contract_no AS ref, status AS detail FROM service_contracts WHERE project_id = ?`, [projectId]);
  add(reviewItems, 'service_contracts', 'Service contracts', serviceContracts);

  const workOrders = await queryAll(
    `SELECT id, wo_no AS ref, status AS detail FROM work_orders WHERE project_id = ? AND status != 'draft'`, [projectId]);
  add(reviewItems, 'work_orders', 'Released Work Orders', workOrders);

  const linkedCertificates = (await queryOne(
    'SELECT COUNT(*) AS n FROM certificate_projects WHERE project_id = ?', [projectId]))?.n || 0;

  return {
    project,
    canDelete: hardBlockers.length === 0 && reviewItems.length === 0, // safe to delete with no confirmation step
    needsReview: hardBlockers.length === 0 && reviewItems.length > 0, // deletable, but only via an explicit "delete anyway"
    hardBlockers,
    reviewItems,
    linkedCertificates, // informational only — deleting the project only drops this association;
    // the certificate itself survives (test_certificates.project_id is ON DELETE SET NULL).
    bomItemCount: bomItemIds.length,
  };
}

export async function deleteProjectCascade(projectId, username, { confirmOverride = false } = {}) {
  // Defense in depth — never trust a caller who skipped the preview.
  const preview = await getProjectDeletePreview(projectId);
  if (!preview) throw new Error('Project not found.');
  if (preview.hardBlockers.length > 0) {
    throw new Error(`This can't be deleted: ${preview.hardBlockers.map(b => b.label).join(', ')}.`);
  }
  if (preview.needsReview && !confirmOverride) {
    const err = new Error('This project has real activity — review it, then confirm to delete anyway.');
    err.needsReview = true;
    err.reviewItems = preview.reviewItems;
    throw err;
  }

  const bomItemIds = await bomItemIdsOf(projectId);

  // Release reservations/serials/pieces the normal way (restores on_hand, notifies Stores) before
  // their own rows are cleared below — outside the transaction, matching this app's own convention
  // that side-effecting release logic stays out of the short DB transaction. Best-effort: a project
  // this stale shouldn't block on a notification hiccup.
  for (const id of bomItemIds) {
    try { await releaseReservationsForItem(id); } catch { /* best-effort */ }
  }

  await withTransaction(async tx => {
    const run = (sql, args = []) => tx.execute({ sql, args });
    const ids = bomItemIds.length ? bomItemIds : [-1];
    const inList = `(${ids.map(() => '?').join(',')})`;

    const qcDocIds = (await tx.execute({ sql: 'SELECT id FROM qc_documents WHERE project_id = ?', args: [projectId] })).rows.map(r => r.id);
    const qcInList = `(${(qcDocIds.length ? qcDocIds : [-1]).map(() => '?').join(',')})`;
    const qcArgs = qcDocIds.length ? qcDocIds : [-1];

    const workOrderIds = (await tx.execute({ sql: 'SELECT id FROM work_orders WHERE project_id = ?', args: [projectId] })).rows.map(r => r.id);
    const woInList = `(${(workOrderIds.length ? workOrderIds : [-1]).map(() => '?').join(',')})`;
    const woArgs = workOrderIds.length ? workOrderIds : [-1];

    const milestoneIds = (await tx.execute({ sql: 'SELECT id FROM milestones WHERE project_id = ?', args: [projectId] })).rows.map(r => r.id);
    const msInList = `(${(milestoneIds.length ? milestoneIds : [-1]).map(() => '?').join(',')})`;
    const msArgs = milestoneIds.length ? milestoneIds : [-1];

    const assemblyIds = (await tx.execute({ sql: 'SELECT id FROM bom_assemblies WHERE project_id = ?', args: [projectId] })).rows.map(r => r.id);
    const asmInList = `(${(assemblyIds.length ? assemblyIds : [-1]).map(() => '?').join(',')})`;
    const asmArgs = assemblyIds.length ? assemblyIds : [-1];

    const calcSheetIds = (await tx.execute({ sql: 'SELECT id FROM calc_sheets WHERE project_id = ?', args: [projectId] })).rows.map(r => r.id);
    const csInList = `(${(calcSheetIds.length ? calcSheetIds : [-1]).map(() => '?').join(',')})`;
    const csArgs = calcSheetIds.length ? calcSheetIds : [-1];

    const drawingIds = (await tx.execute({ sql: 'SELECT id FROM calc_drawings WHERE project_id = ?', args: [projectId] })).rows.map(r => r.id);
    const dwInList = `(${(drawingIds.length ? drawingIds : [-1]).map(() => '?').join(',')})`;
    const dwArgs = drawingIds.length ? drawingIds : [-1];

    // Financial documents that carry their own stored totals / possible GL posting — sever the
    // link, never delete the row. Everything downstream of them (items/payments/receipts/credit
    // notes on an invoice; the bill's own totals) stays exactly as it was.
    await run(`UPDATE vendor_bill_items SET bom_item_id = NULL WHERE bom_item_id IN ${inList}`, ids);
    await run(`UPDATE sales_invoices SET project_id = NULL WHERE project_id = ?`, [projectId]);

    // Purchase Orders — only this project's own lines are removed (a PO can span projects); the
    // header itself only goes once it has zero items left AND no surviving Vendor Bill still points
    // at it (vendor_bills.po_id is NOT NULL with no ON DELETE clause — a bill against this PO for
    // another project's material would otherwise dangle). purchase_orders carries no stored total
    // of its own (computed at read time), so removing just this project's lines never leaves a
    // stale aggregate on it.
    const affectedPoIds = (await tx.execute({ sql: `SELECT DISTINCT po_id FROM po_items WHERE bom_item_id IN ${inList}`, args: ids })).rows.map(r => r.po_id);
    await run(`DELETE FROM po_items WHERE bom_item_id IN ${inList}`, ids);
    for (const poId of affectedPoIds) {
      const remaining = (await tx.execute({ sql: 'SELECT COUNT(*) AS n FROM po_items WHERE po_id = ?', args: [poId] })).rows[0].n;
      const billsAgainstIt = (await tx.execute({ sql: 'SELECT COUNT(*) AS n FROM vendor_bills WHERE po_id = ?', args: [poId] })).rows[0].n;
      if (remaining === 0 && billsAgainstIt === 0) await run('DELETE FROM purchase_orders WHERE id = ?', [poId]);
    }

    // Ownership tags on shared physical stock — nulled, never deleted or dropped from history.
    await run('UPDATE stock_pieces SET project_id = NULL WHERE project_id = ?', [projectId]);
    await run('UPDATE stock_pieces SET owner_project_id = NULL WHERE owner_project_id = ?', [projectId]);
    await run('UPDATE inventory_batches SET project_id = NULL WHERE project_id = ?', [projectId]);
    await run('UPDATE inventory_serials SET project_id = NULL WHERE project_id = ?', [projectId]);

    // Records CASCADE off projects/qc_documents but carry their own NO-ACTION edges elsewhere —
    // must go before the tables those edges point at, since the CASCADE for these only fires on the
    // final DELETE FROM projects (too late for anything below).
    await run('DELETE FROM ncr_records WHERE project_id = ?', [projectId]);
    await run('DELETE FROM job_work_inspections WHERE project_id = ?', [projectId]);
    await run(`DELETE FROM qc_document_parts WHERE document_id IN ${qcInList}`, qcArgs);
    await run(`DELETE FROM qc_mountings WHERE document_id IN ${qcInList}`, qcArgs);
    await run(`DELETE FROM qc_iiia_groups WHERE document_id IN ${qcInList}`, qcArgs);
    await run(`DELETE FROM qc_document_longitudinal_seams WHERE document_id IN ${qcInList}`, qcArgs);
    await run(`DELETE FROM qc_form4a_groups WHERE document_id IN ${qcInList}`, qcArgs);
    await run('DELETE FROM qc_records WHERE project_id = ?', [projectId]);

    // Material received/issued, and reservation-adjacent rows (releaseReservationsForItem above
    // already flipped status/on_hand). Supplier quotes need no explicit statement — CASCADE off
    // bom_items cleans them up automatically once bom_items are deleted below.
    await run(`DELETE FROM bom_item_receipts WHERE bom_item_id IN ${inList}`, ids);
    await run(`DELETE FROM material_issues WHERE bom_item_id IN ${inList}`, ids);
    await run(
      `DELETE FROM inventory_batch_allocations WHERE reservation_id IN
       (SELECT id FROM inventory_reservations WHERE bom_item_id IN ${inList})`, ids);
    await run(`DELETE FROM inventory_reservations WHERE bom_item_id IN ${inList}`, ids);
    await run(`DELETE FROM rfq_items WHERE bom_item_id IN ${inList}`, ids);
    await run(`DELETE FROM work_order_materials WHERE bom_item_id IN ${inList}`, ids);
    await run(`DELETE FROM bom_change_notes WHERE bom_item_id IN ${inList} OR project_id = ?`, [...ids, projectId]);
    await run(
      `DELETE FROM material_indent_items WHERE bom_item_id IN ${inList}
       OR indent_id IN (SELECT id FROM material_indents WHERE project_id = ?)`, [...ids, projectId]);
    await run(`DELETE FROM bom_item_child_allocations WHERE bom_item_id IN ${inList} OR child_project_id = ?`, [...ids, projectId]);
    await run(`DELETE FROM bom_item_child_routing WHERE bom_item_id IN ${inList} OR child_project_id = ?`, [...ids, projectId]);
    await run(`DELETE FROM bom_item_child_certificates WHERE bom_item_id IN ${inList} OR child_project_id = ?`, [...ids, projectId]);
    await run(`DELETE FROM bom_item_expected_children WHERE child_project_id = ?`, [projectId]);

    // Self-referencing resubmission chains — one blanket DELETE per table is safe: the whole
    // project-scoped set disappears together, so no NO-ACTION check (evaluated at statement end)
    // is ever left with a dangling row (same reasoning app/api/projects/[id]/clear-bom already
    // relies on for bom_assemblies' own self-referencing parent_id).
    await run(`DELETE FROM inward_approvals WHERE project_id = ? OR bom_item_id IN ${inList}`, [projectId, ...ids]);
    await run(`DELETE FROM pre_dispatch_approvals
      WHERE project_id = ? OR packing_list_id IN (SELECT id FROM packing_lists WHERE project_id = ?)`, [projectId, projectId]);

    await run(`DELETE FROM job_cards WHERE project_id = ? OR work_order_id IN ${woInList} OR milestone_id IN ${msInList}`, [projectId, ...woArgs, ...msArgs]);
    await run(`DELETE FROM material_indents WHERE project_id = ?`, [projectId]);
    await run(`DELETE FROM work_orders WHERE project_id = ?`, [projectId]);

    // The BOM itself.
    await run(`DELETE FROM bom_items WHERE project_id = ?`, [projectId]);
    await run(`DELETE FROM bom_assembly_drawings WHERE assembly_id IN ${asmInList}`, asmArgs);
    await run(`DELETE FROM bom_assembly_calc_sheets WHERE assembly_id IN ${asmInList}`, asmArgs);
    await run(`DELETE FROM bom_assemblies WHERE project_id = ?`, [projectId]);

    // Engineering/Design documents.
    await run(`DELETE FROM calc_sheet_drawings WHERE calc_sheet_id IN ${csInList}`, csArgs);
    await run(`DELETE FROM calc_drawing_files WHERE drawing_id IN ${dwInList}`, dwArgs);
    await run(`DELETE FROM calc_drawing_comments WHERE drawing_id IN ${dwInList}`, dwArgs);
    await run(`DELETE FROM calc_drawings WHERE project_id = ?`, [projectId]);
    await run(`DELETE FROM calc_sheets WHERE project_id = ?`, [projectId]);
    await run(`DELETE FROM scope_of_supply WHERE project_id = ?`, [projectId]);
    await run(`DELETE FROM pr_item_projects WHERE project_id = ?`, [projectId]);

    // Packing lists — genuinely project-owned (no stored total of its own), safe to delete
    // outright regardless of status. Their sales_invoice_id link is nulled first — the invoice
    // itself survives (see above), only its own now-project-less identity remains.
    await run(`UPDATE packing_lists SET sales_invoice_id = NULL WHERE project_id = ?`, [projectId]);
    await run(`DELETE FROM packing_lists WHERE project_id = ?`, [projectId]);

    await run(`DELETE FROM bom_release_snapshots WHERE project_id = ?`, [projectId]);
    await run('DELETE FROM service_calls WHERE project_id = ?', [projectId]);
    await run('DELETE FROM service_contracts WHERE project_id = ?', [projectId]);

    // Last: the project row itself. Everything else project-owned is CASCADE off it directly
    // (milestones, bom_imports, qc_documents, tickets, notifications, procurement_requests,
    // certificate_projects, job_card_* via already-deleted job_cards, item_link_memory).
    await run(`DELETE FROM projects WHERE id = ?`, [projectId]);
  });
}
